workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app

    publishing:
      app_store_connect:
        api_key:
          key_id: 4SZAB6635B
          issuer_id: Tafeb26af-25c9-4075-bcfa-d664c3c60cf0
          private_key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgq03+qq4thzb8FjZ/
            KVKFmT5qKMte2ToRFpH38njfPdigCgYIKoZIzj0DAQehRANCAAR74uNY+eNFh7Gs
            vUD3PBzfmKkGzvIShW7LMoz563NuBxYFEFIn4zLRmeOM9qnvXeOqKloeA1XCt/uo
            WsGjhdBA
            -----END PRIVATE KEY-----
        submit_to_testflight: true