// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JwNUNZvZFPG7k2443RZSp5YTDohuXxI',
    appId: '1:34926212535:web:499e36a2e90df02215e432',
    messagingSenderId: '34926212535',
    projectId: 'budgetapp-7935b',
    authDomain: 'budgetapp-7935b.firebaseapp.com',
    storageBucket: 'budgetapp-7935b.firebasestorage.app',
    measurementId: 'G-VBG2DR03RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnzZAKx4DT_h8iMIoIo4-DkCi2DMzli8',
    appId: '1:34926212535:android:9769873b7c22562e15e432',
    messagingSenderId: '34926212535',
    projectId: 'budgetapp-7935b',
    storageBucket: 'budgetapp-7935b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVONcxvkvd_VN0ru6DJSXYC2VBzZ7Xrc',
    appId: '1:34926212535:ios:3d7990450c4a72a215e432',
    messagingSenderId: '34926212535',
    projectId: 'budgetapp-7935b',
    storageBucket: 'budgetapp-7935b.firebasestorage.app',
    iosBundleId: 'com.dimitri.budgetapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVONcxvkvd_VN0ru6DJSXYC2VBzZ7Xrc',
    appId: '1:34926212535:ios:8b37c23825ffb03515e432',
    messagingSenderId: '34926212535',
    projectId: 'budgetapp-7935b',
    storageBucket: 'budgetapp-7935b.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-JwNUNZvZFPG7k2443RZSp5YTDohuXxI',
    appId: '1:34926212535:web:c8b9893243f4e00615e432',
    messagingSenderId: '34926212535',
    projectId: 'budgetapp-7935b',
    authDomain: 'budgetapp-7935b.firebaseapp.com',
    storageBucket: 'budgetapp-7935b.firebasestorage.app',
    measurementId: 'G-4YVLPFEKT3',
  );
}
